name: tensopay_wallet_prototype
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  http: ^0.13.4
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  build_runner: ^2.1.7
  web_socket_channel: ^2.1.0
  qr_code_scanner: ^0.7.0
  intl: ^0.17.0
  custom_navigation_bar: ^0.8.2
  nb_utils: ^4.4.11
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  otp_text_field: ^1.1.2
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
      - assets/images/
      - assets/images/splash_screen/